### ISSUE TITLE
Client & server - subscribe events

### ISSUE THREAD

**Issue by yboujraf** [dufourgilles/node-emberplus#1]
Dear @dufourgilles 

I need to retest all what I did after you last great update.

### Events

To complete my test, I need to know how server and client could subscribe to the events :

**From server :**
- connect client
- disconnect client
- keepalive,
- getDirectory requested,  
- the client at first connection, the server will send his directory when small devices
 ...., 
- set value,
- un/subscribe to a parameter from which client

**From client :**
- getdirectory received after connection (small device push directly the directory to the client without requests) 

Otherwise I don't know if you tried to reach me by phone. Better If you could share through MP your mobile or through linkedin.

Best Regards
Youssef

**Comment by dufourgilles** [comment]
By default, if you do a getDirectory on a parameter or a matrix, the client is automatically subscribed to any change on that component unless a streamidentified has been set on that component.

**Comment by yboujraf** [comment]
Dear @dufourgilles 

Thanks for the feedback.

### Topic StreamIdentifier

I have found in device.js, for subscribe and unsubscribe mentionned TODO.
I don't know if there is any relation with this.

Or in my device, I have many StreamIdentifier but could enabling because offline (no audio).

![image](https://user-images.githubusercontent.com/6151258/70849033-93563d00-1e79-11ea-8bde-fe289a2d0872.png)

How the client could un/subscribe? 
Because I have double checked, when EmberPlusViewer  un/subscribe, himself he decides or not to update his value even the server broadcast the data.


### Topic EmberPlusViewer client subscribe the streamidentifier

[Client-subscribes-Stream.zip](https://github.com/dufourgilles/node-emberplus/files/3963854/Client-subscribes-Stream.zip)

### Topic EmberPlusViewer client unsubscribe the streamidentifier

[Client-unsubscribes-Stream.zip](https://github.com/dufourgilles/node-emberplus/files/3963855/Client-unsubscribes-Stream.zip)
subscribe the streamidentifier

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear @dufourgilles 

I have seen in your last commit that you have implemented the un/subscribe for the client side.

Is it right ?

Best Regards,
Youssef

**Comment by dufourgilles** [comment]
correct.

**Comment by yboujraf** [comment]
Dear @dufourgilles 

I will try it tomorrow 

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear @dufourgilles 

Just if we could have the list of events for server and client could be great.

Best Regards
Youssef

**Comment by dufourgilles** [comment]
Hello Youssef.
I have created a new version 2.0.  Complete rewrite using ES6 format.
A lot of the functions had duplicate code.  It was necessary to do some cleanup.
Check the new README.md as the require statements are now different.

The server will now emit "event" that you can catch to create your list of events.

server.on("event", event => {
        console.log("Event: " + event);
    });

Here is the output :

Event: getdirectory to root(path: ) from 192.168.1.99:63769
Event: getdirectory to scoreMaster(path: 0) from 192.168.1.99:63769
Event: getdirectory to identity(path: 0.0) from 192.168.1.99:63769
Event: set value for version(0.0.2) from local
Event: subscribe to version(path: 0.0.2) from 192.168.1.99:63769
Event: set value for version(0.0.2) from local
Event: getdirectory to router(path: 0.1) from 192.168.1.99:63769
Event: Matrix connection to matrix(path: 0.1.0) target 0 connections: 1 from 192.168.1.99:63769
