### ISSUE TITLE
subscription doesn't work on v2

### ISSUE THREAD

**Issue by dewiweb** [dufourgilles/node-emberplus#10]
Hello @dufourgilles ,
I've tested  launch a subscription to a fader level parameter with your code example.
But when I made modification on this parameter (server side) nothing appears in the console. 

Dewiweb

**Comment by dufourgilles** [comment]
There is indeed a problem.
Working on it.

**Comment by dufourgilles** [comment]
Please test 2.5.7

**Comment by dewiweb** [comment]
Apparently,
 still the same with 2.5.7

**Comment by dewiweb** [comment]
Xcuse me,
It seems to work but only with this part of the example :
```javascript
.then(() => client.getElementByPath("path/to/node", update => {console.log(update.contents.value);}))
```

**Comment by dufourgilles** [comment]
I tested all 3 scenarios.

.then(() => client.getElementByPath("0.0.1"))
.then(node => {
   console.log(node);
   return client.getDirectory(node, update => {console.log("update:", update);});
})
.then(() => client.getElementByPath("0.0.2"))
.then(node => {
   console.log(node);
   return client.subscribe(node, update => {console.log("update:", update);});
})


It works for me.
Provide more details if you still have an issue.

**Comment by dewiweb** [comment]
I beg your pardon, It was  a syntax error on my side.
After another test (on non-stream parameter), It works.
You can close this issue.

Many thanks.

Best regards
