### ISSUE TITLE
EmberServer: Stream parameters error

### ISSUE THREAD

**Issue by olzzon** [dufourgilles/node-emberplus#13]
When having a stream in a children group, all children in that group is not send to client when asking for full tree (.expand) though it's still in the EmberServer.tree
 
```
{
                                        "nodeType": "Parameter",
                                        "number": 9,
                                        "path": "1.2.5.1.9",
                                        "identifier": "PeakValue_2",
                                        "type": 2,
                                        "streamIdentifier": 4,
                                        "streamDescriptor": {
                                            "format": "ieeeFloat32LittleEndian",
                                            "offset": 4
                                        },
                                        "access": 1,
                                        "maximum": 20,
                                        "minimum": -200,
                                        "value": -200
                                    }
```

**Comment by olzzon** [comment]
In ParametersContent.js the code assumes that there's a encode function in this.streamDescriptor

<img width="327" alt="image" src="https://user-images.githubusercontent.com/29782499/75773023-58afc280-5d4d-11ea-9412-e64fe30516af.png">

Setting up a server with following ember tree can show the bug:
```
[
    {
        "nodeType": "Node",
        "number": 1,
        "path": "1",
        "isOnline": true,
        "identifier": "R3LAYVRX4",
        "description": "",
        "schemaIdentifiers": "",
        "children": [
            {
                "nodeType": "Node",
                "number": 1,
                "path": "1.2.5.1",
                "isOnline": true,
                "identifier": "FaderSlot_1",
                "description": "",
                "schemaIdentifiers": "",
                "children": [
                    {
                        "nodeType": "Parameter",
                        "number": 9,
                        "path": "1.2.5.1.9",
                        "identifier": "PeakValue_2",
                        "type": 2,
                        "streamIdentifier": 4,
                        "streamDescriptor": {
                            "format": "ieeeFloat32LittleEndian",
                            "offset": 4
                        },
                        "access": 1,
                        "maximum": 20,
                        "minimum": -200,
                        "value": -200
                    }
                ]
            }
        ]
    }
]
```

**Comment by dufourgilles** [comment]
The streamDescriptor should be of type StreamDescription.
You can see it in the decode function

                case BER.CONTEXT(16):
                    pc.streamDescriptor = StreamDescription.decode(seq);
                    break;

However, the json2tree function does not support streamDescriptor at the moment.
So, if you create your tree from json on the server, you need to modify the tree to use the right object type.
ie:
paramter.contents.streamDescriptor = new StreamDescription();
paramter.contents.streamDescriptor.offset = 4;
paramter.contents.streamDescriptor.format = StreamFormat.ieeeFloat32LittleEndian

G.

**Comment by dufourgilles** [comment]
Please test 2.5.8.
I have added support for streamDescriptor in the json2tree and tested with your provided tree.
It now works for me.

![image](https://user-images.githubusercontent.com/16135147/75992543-68b7d580-5ef8-11ea-9e20-af3b27d349ef.png)

**Comment by olzzon** [comment]
2.5.8 is working, thanks, and now I know where to look next time 👍 
I´m using json2tree to create the tree for the serverside, but also to "clone" another server for testing.
https://github.com/olzzon/tv2-rest-ember-gateway.git

**Comment by olzzon** [comment]
Closing it as it's fixed. Thanks a lot for all your great work!!
