### ISSUE TITLE
Matrix : Labels - how to add the description ?

### ISSUE THREAD

**Issue by yboujraf** [dufourgilles/node-emberplus#2]
Dear @dufourgilles 

I tried the new fork and I discovered :

### Topic How to define the description in the MatrixContents - Labels [10] 

I have no issue to create multiple label layers but can't define a description for each layer.

`                        labels: ["0.20.1000", "0.20.2000"]`

and in EmberPlusViewer, he detect the two layers and I can select the Label but not see the description

![image](https://user-images.githubusercontent.com/6151258/70689421-83413080-1cb4-11ea-8248-fd86b30cc7e7.png)

```
</Root><Root Type="ElementCollection">
  <Matrix Path="0.20.1">
    <Contents>
      <AddressingMode>0</AddressingMode>
      <TargetCount>5</TargetCount>
      <SourceCount>5</SourceCount>
      <Labels>
        <Label BasePath="0.20.1000" Description="" />
        <Label BasePath="0.20.2000" Description="" />
      </Labels>
    </Contents>
    <Children />
    <Connections>
      <Connection Target="0" />
      <Connection Target="1" />
      <Connection Target="2" />
      <Connection Target="3" />
      <Connection Target="4" />
    </Connections>
  </Matrix>
</Root>
```

### TinyEmber - Label is decoded by the ember client

![image](https://user-images.githubusercontent.com/6151258/70689483-b5eb2900-1cb4-11ea-8fc5-91a4e8d07ea8.png)

#### With EmberPlusViewer logger

<Matrix Path="1.2.3">
    <Contents>
      <Identifier>matrix</Identifier>
      <AddressingMode>1</AddressingMode>
      <TargetCount>4</TargetCount>
      <SourceCount>4</SourceCount>
      <ParametersLocation LocationKind="RELATIVE-OID">1.2.2</ParametersLocation>
      <Labels>
        <Label BasePath="1.2.1" Description="Primary" />
      </Labels>
    </Contents>
    <Children />
  </Matrix>

And the ember client

```
                            "labels": [
                                {
                                    "basePath": "1.1.1",
                                    "description": "Primary"
                                }
                            ],
```

But don't know how to declare it ?

Is it missing here some metadatas ?

`                        labels: ["0.20.1000", "0.20.2000"]`

### Ember.js

I found label.encode and label.decode and all have description attribute.

`
Label.decode = function(ber) {
    var l = new Label();

    ber = ber.getSequence(BER.APPLICATION(18));

    while (ber.remain > 0) {
        var tag = ber.peek();
        var seq = ber.getSequence(tag);
        if (tag == BER.CONTEXT(0)) {
            l.basePath = seq.readRelativeOID(BER.EMBER_RELATIVE_OID);
        } else if (tag == BER.CONTEXT(1)) {
            l.description = seq.readString(BER.EMBER_STRING);
        }
        else {
            throw new errors.UnimplementedEmberTypeError(tag);
        }
    }
    return l;
};

Label.prototype.encode = function(ber) {
    ber.startSequence(BER.APPLICATION(18));
    if (this.basePath !== undefined) {
        ber.startSequence(BER.CONTEXT(0));
        ber.writeRelativeOID(this.basePath, BER.EMBER_RELATIVE_OID);
        ber.endSequence();
    }
    if (this.description !== undefined) {
        ber.startSequence(BER.CONTEXT(1));
        ber.writeString(this.description, BER.EMBER_STRING);
        ber.endSequence();
    }
    ber.endSequence();
}

`I hope it could help you

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear @dufourgilles 

Thanks in advance if you could check this too

**Comment by dufourgilles** [comment]
Should be fixed in 1.10.1
New format for label definition
labels: [{basePath: "0.1.1000", description: "primary"}]

**Comment by yboujraf** [comment]
Dear @dufourgilles 

Will check it.

Best Regards,

**Comment by yboujraf** [comment]
Dear @dufourgilles

If I am more level of labels do I need to do like this :

```
labels: [{
    "basePath": "0.1.1000",
    "description": "primary"
},
{
    "basePath": "0.1.2000",
    "description": "secondary"
}
]
```

Best Regards,
Youssef

**Comment by dufourgilles** [comment]
Yes

**Comment by yboujraf** [comment]
Dear @dufourgilles 

![image](https://user-images.githubusercontent.com/6151258/70850456-bfc68500-1e8a-11ea-800c-d2e77a750683.png)

The labels work fine unfortunately, EmberPlusViewer is not updating the label level but I am quite sure it worked before. Will check with other tools.

Best Regards,
Youssef

**Comment by dufourgilles** [comment]
The description is now visible.  I will close this issue.
If you have further issue, open a new entry.
Thanks.
