### ISSUE TITLE
MAtrix - OneToN - More than one connections could be made

### ISSUE THREAD

**Issue by yboujraf** [dufourgilles/node-emberplus#3]
Dear @dufourgilles 

I tried again with the new fork and :

### Topic - Disconnect in EmberPlusViewer is now enabled and working
But for a matrix type OneToN, this behaviour can't be done only nTon or 1to1

### Topic - Matrix type OneToN still possible to switch more than one crosspoint to the same target.

Best Regards
Youssef

**Comment by dufourgilles** [comment]
I’m looking  into it.

**Comment by yboujraf** [comment]
Dear @dufourgilles 

Thanks in advance

**Comment by dufourgilles** [comment]
Please test version 1.10.2
Added a function to check connection request before applying changes.

**Comment by yboujraf** [comment]
Dear @dufourgilles 

Since this update, I am not able to make any crosspoint.

Only one that's all.

![image](https://user-images.githubusercontent.com/6151258/70850489-23e94900-1e8b-11ea-9867-34cb2841295e.png)


Best Regards,
Youssef

**Comment by dufourgilles** [comment]
What kind of Matrix ?
Now are enforcing the 1-1 or 1-N rules.

**Comment by dufourgilles** [comment]
ok. I see the problem.
Fix is coming

**Comment by yboujraf** [comment]
Dear @dufourgilles 

Thank for your contribution.
I will not forget you.

This is the final round ;-)

Best Regards,
Youssef
