### ISSUE TITLE
Timeout - when tree.expand(tree.root.elements[0]) for large ember+ tree

### ISSUE THREAD

**Issue by yboujraf** [dufourgilles/node-emberplus#4]
Dear @dufourgilles 

I am trying to just expand the root of a router and I got a multi nodes and this is the main tree

`        
await tree.getDirectory();
await tree.expand(tree.root.elements[0]);
`

![image](https://user-images.githubusercontent.com/6151258/70736199-178cb100-1d10-11ea-886a-85b5de3c3449.png)

Each node has sub directory, qualified Matrix, Qualified function, .... and taking times to parse.

### Topic - Timeout

`desk01@BY_DESKTOP_01 MINGW64 /c/Git/_EMBERPLUS/node-emberplus-master
$ node ./usecases/GetDirectory/main-discoverclient.js
- Connecting to 192.168.0.234:9000 ...
- Discovering ...
Discover error ! EmberTimeoutError: Request 1 - 2 timed out
    at DeviceTree.timeoutRequest (C:\Git\_EMBERPLUS\node-emberplus-master\device.js:396:29)
    at Timeout.<anonymous> (C:\Git\_EMBERPLUS\node-emberplus-master\device.js:355:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'EmberTimeoutError',
  message: 'Request 1 - 2 timed out'
}`

I tried to extend to million the timeout but still the same then my conclusion is to parse each node and getDirectory of each node ? is it right ?

Best regards,
Youssef

**Comment by yboujraf** [comment]
Dear @dufourgilles 

If you see the last picture attached in this issue, you can see we have an array of elements.
But when tried to getDirectory to one of the elements we have an error.

![image](https://user-images.githubusercontent.com/6151258/70793607-f96c9280-1d9b-11ea-8bdf-a933e24e3e4f.png)


I created a small device with two elements (tree.root.elements[0] & tree.root.elements[1]) with few nodes and it works the getDirectory.
But if it is a router device like the screenshot we have immediately timeout.
With emberPlusViewer, no issue

I can share a connection of the device if you want to test it. The device is offair

Best Regards
Youssef

**Comment by dufourgilles** [comment]
Looks like the connection was closed.
If you can open a hole in your firewall for me to reach that device, I can debug it to see what is going on.
Please share the info privately dufour.gilles@gmail.com

**Comment by yboujraf** [comment]
Dear @dufourgilles 

I sent you an email with all the information

Best Regards,
Youssef

**Comment by dufourgilles** [comment]
I connected to your setup and could debug the issue.
A fix is now available in 1.10.3

**Comment by yboujraf** [comment]
Dear

Great job.

Will check it out and let you know.

Best regards
Youssef

**Comment by yboujraf** [comment]
Dear @dufourgilles 

One line of code for fixing this ;-)

### Topic Expand an Elements[] in a tree structure

Example expand of Elements[0] of the equipment shared to you.

[test-discover_path_0.zip](https://github.com/dufourgilles/node-emberplus/files/3963922/test-discover_path_0.zip)

Now when I expand any elements[] I can see in the Tree structure a new TAG "path" then "number"
It looks like correct for me.

=> Do we need to construct the tree as well ?

### Topic Expand of Elements[0] from tinyEmberRouer

[test-discover_path_1_tinyember.zip](https://github.com/dufourgilles/node-emberplus/files/3963929/test-discover_path_1_tinyember.zip)

I can find only the TAG "PATH" everywhere even on children with full path.

Is it because the device send you like this or there is any properties not setted correctly in the TinyemberRouter.

My position is First topic, PATH TAG for Elements[] and number TAG for each children then your tree structure could be reuse for emulate any device without changing anything in the data model.

Is it right?

Best Regards,
Youssef

**Comment by dufourgilles** [comment]
the path and number are just internal representation.
You can always get the value for any node using getNumber or getPath.

Example:

    console.log(client.root.elements[0].children[0].getNumber(), client.root.elements[0].children[0].getPath());

With this node :

QualifiedNode {
  path: '1.0',
  contents: NodeContents { isOnline: true, identifier: 'identity' },
  children:
   [ QualifiedParameter { path: '1.0.1', contents: [ParameterContents] },
     QualifiedParameter { path: '1.0.2', contents: [ParameterContents] },
     QualifiedParameter { path: '1.0.3', contents: [ParameterContents] } ] }

We get

0 '1.0'

**Comment by yboujraf** [comment]
Dear @dufourgilles 

When making an expand we get path instead of “number” or both

That’s why I am confused.

If I generate a new device model, could I use “number” or “path”  to identify a node, a parameter, matrix, functions,….

Or it is mandatory to use “number” as recommended by the specification.

Then when I expand I need to have "number" instead of "path"

Two expand from two different devices.

[test-discover_path_0.zip](https://github.com/dufourgilles/node-emberplus/files/3967373/test-discover_path_0.zip)

[test-discover_path_1_tinyember.zip](https://github.com/dufourgilles/node-emberplus/files/3967374/test-discover_path_1_tinyember.zip)

Best Regards,
Youssef

**Comment by dufourgilles** [comment]
QualifiedNode uses path
Node uses number.








But as I said, you can use getNumber() on a QualifiedNode or getPath() on a Node and that will work.

If you build your own tree, you can use whatever format you like.
But if you wants to use the jsontotree function, you need to use number.

G.

**Comment by yboujraf** [comment]
Dear @dufourgilles 

So I will use the data model from Lawo router.

Path for the main node = Elements[]
number for the rest

Could you confirm ? then I will generate a new device model and try it as server.

Best Regards,
Youssef
