### ISSUE TITLE
ASN1 library : to keep independent and use the main repository up to date with ES6

### ISSUE THREAD

**Issue by yboujraf** [dufourgilles/node-emberplus#6]
Dear @dufourgilles Gilles,

Is there a way to not use the ASN1 repository from EVS but from the owner?

```
  "dependencies": {
    "asn1": "github:evs-broadcast/node-asn1#date_2018_01_02",
```

To keep this repository totally independent

```
https://github.com/joyent/node-asn1 
```

But be careful is also rewritten in ES6 and there are some issues but not sure it was same issues already existing when forked 2 years ago ?

Thanks to verify.

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear @dufourgilles 

I have seen that in the original ASN1 repo they support all the types https://github.com/joyent/node-asn1/blob/master/lib/ber/types.js

Nice to have it to because mentionned in the Ember+ specification. (but not priority)

Best Regards
Youssef

**Comment by dufourgilles** [comment]
Original branch does not have support for BER block with unknown size, relativeOID, 64 bits counters... can't use it
