### ISSUE TITLE
Examples to interact with server!

### ISSUE THREAD

**Issue by dewiweb** [dufourgilles/node-emberplus#7]
Hello,
Could you add, please, some examples to change parameters values?
Bmayton (initiator of node-emberplus) had this example in his readme but I don't know if it's still functional:

## Example usage

```javascript
const DeviceTree = require('emberplus').DeviceTree;
var tree = new DeviceTree("localhost", 9998);
tree.on('ready', () => {
    tree.getNodeByPath("EmberDevice/Sources/Monitor/Amplification").then((node) => {
        
        // Subscribe to parameter changes
        tree.subscribe(node, (node) => {
            console.log("Volume changed: %d", node.contents.value);
        });
        // Change parameter value
        tree.setValue(node, -20.0);
    }).catch((e) => {
        console.log("Failed to resolve node:", e);
    });
});

**Comment by dufourgilles** [comment]
To Change a value:

const client = new EmberClient(LOCALHOST, PORT);
await client.connect()
await client.getDirectory();
await client.getElementByPath("0.0.1");
await client.setValue(client.root.getElementByPath("0.0.1"), "gdnet");
console.log("result", server.tree.getElementByPath("0.0.1").contents.value)
return client.disconnect().then(() => { console.log("disconnected")});



To subscribe

const {EmberClient, EmberLib} = require('node-emberplus');

const client = new EmberClient(HOST, PORT);
client.connect())
   .then(() => client.getDirectory())
   .then(() => {console.log(JSON.stringify(client.root.toJSON(), null, 4));})
   .then(() => client.getElementByPath("scoreMaster/router/labels/group 1"))
   .then(node => {
      // For streams, use subscribe
      return client.subscribe(node, update => {
         console.log(udpate);
      });
   })
   .then(() => client.getElementByPath("0.2"))
   .then(node => {
      // For non-streams a getDirectory will automatically subscribe for update
      return client.getDirectory(node, update => {
         console.log(udpate);
      });
   })
   // You can also provide a callback to the getElementByPath
   // Be carefull that subscription will be done for all elements in the path
   .then(() => client.getElementByPath("0.3", update => {console.log(update);}))
   ;
