### ISSUE TITLE
Lawo MC² incompatibility

### ISSUE THREAD

**Issue by dewiweb** [dufourgilles/node-emberplus#9]
Hi @dufourgilles , 
it seems that your recent work breaks something about compatibility with lawo mc² consoles...(or maybe Lawo have applied modifications in their provider)
We can't anymore traverse MC² ember tree and access directly to a parameter.  Apparently, it's necessary to iterate requests to the provider (first node level, then second level,then third level..). It's not possible to change a parameter directly with like explained in your example.
#8

**Comment by vashat** [comment]
We tried to troubleshoot the project and It seams that the first nodes in the ember+ tree are treated as  leaf nodes so the children under it are not listed (since leafs don't have children).

**Comment by dufourgilles** [comment]
Please test 2.5.6
I had the same issue as well and fixed it there.

**Comment by vashat** [comment]
Yes works perfectly now. Thank you very much for this!
